name: Skepsi
markdown: kramdown
# Bogus extension, so that the markdown plugin can
# find the Markdown files instead
markdown_ext: hide_markdown
kramdown:
  auto_ids: false
sass:
  sass_dir: assets/_sass
highlighter: 'pygments'
lsi: false
encoding: 'UTF-8'
exclude: [vendor]
