baseURL = "https://voithos.io/"
languageCode = "en-us"
title = "voithos.io"
pagination.pagerSize = 10
enableEmoji = true

[params]
author = "Zaven Muradyan"
description = "Personal site of Zaven Muradyan"
mainSections = ['articles']

[markup.highlight]
style = 'dracula'

[markup.goldmark.renderer]
unsafe = true

[outputFormats.RSS]
baseName = "feed"
