baseURL = "https://voithos.io/"
languageCode = "en-us"
title = "voithos.io"
paginate = 10
enableEmoji = true

[params]
mainSections = ['articles']

[markup.highlight]
style = 'doom-one2'

[markup.goldmark.renderer]
unsafe = true
