baseURL = "https://voithos.io/"
languageCode = "en-us"
title = "voithos.io"
paginate = 10
enableEmoji = true

[params]
author = "Zaven Muradyan"
description = "Personal site of Zaven Muradyan"
mainSections = ['articles']

[markup.highlight]
style = 'doom-one2'

[markup.goldmark.renderer]
unsafe = true

[outputFormats.RSS]
baseName = "feed"
